### ISSUE TITLE
WinGet Publishing bug Causes issues with installing modern Suwayomi versions (including on UniGetUI (Package manager GUI))

### ISSUE THREAD

**Issue by RandomPersonUMet** [AriaMoradi/Tachidesk#1503]
### Steps to reproduce

1. Search for Suwayomi-Server on UniGetUI
2. Run WinGet command (below) or Click Install on UniGetUI
3. Run installed Suwayomi Server and go to Settings>About

`winget.exe install --id "Suwayomi.Tachidesk-Server" --exact --source winget --accept-source-agreements --disable-interactivity --silent  --accept-package-agreements --force `

<img width="1667" height="344" alt="Image" src="https://github.com/user-attachments/assets/46a704c0-f144-4d4c-a083-2f334d959d81" />

### Expected behavior

Server Version should be _**v2.0.1727**_.

### Actual behavior

Server Version is _**v1.0.0**_.

<img width="463" height="587" alt="Image" src="https://github.com/user-attachments/assets/6b14ff98-767d-4ac2-8579-8b699dc284a5" />

### Suwayomi-Server version

v2.0.1727

### Server operating system

Windows 10 Pro 22H2

### Server JVM version

OpenJDK Platform 21.0.6.0

### Used client name

Suwayomi-WebUI

### Client version

r2643

### Used web browser

Chrome 138.0.7204.97 (Official Build) (64-bit)

### Client operating system

Windows 10 Pro 22H2

### Explanation
On [UniGetUI (a Windows package manager GUI)](https://github.com/marticliment/UniGetUI) Suwayomi doesn’t appear properly, as it has the previous Tachidesk name, as well as being a severely outdated version of Suwayomi (UniGetUI uses WinGet).

This is an issue, as I use UniGetUI to manage my application updates in a centralised and convenient way, plus I would also find it helpful to share Suwayomi with my friends (who aren't knowledgeable/comfortable with using GitHub) through UniGetUI’s package bundle feature (you can preset install configs).

I tried to figure out why and found [this on the GitHub page](https://github.com/Suwayomi/Suwayomi-Server/actions/workflows/winget.yml), with lots of errors and [the winget.yml script](https://github.com/Suwayomi/Suwayomi-Server/blob/master/.github/workflows/winget.yml) which has the identifier set as “Suwayomi.Tachidesk-Server”. I imagine that this could be the issue.

### My Experience

1. Searching for Suwayomi Package

<img width="940" height="194" alt="Image" src="https://github.com/user-attachments/assets/65fcc16e-4369-4e1f-9fcd-de488160556a" />

2. Official but severely outdated Suwayomi Package (installed version shows _2.0.1727_ on my PC with the manually installed Suwayomi Package, but returns _NULL_ on my VM with the Suwayomi Package installed using WinGet)

<img width="940" height="299" alt="Image" src="https://github.com/user-attachments/assets/f0fdde2d-d2f9-4c14-92c8-6235d2ab43a8" />

3. Installed Suwayomi Server Package showing outdated version number (_v1.0.0_)

<img width="724" height="917" alt="Image" src="https://github.com/user-attachments/assets/464d55a2-402b-4fbd-9f66-ed61b8d7b9c4" />

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title (ideally less than ~100 characters).
- [x] I have tried the troubleshooting guide described in [README.md](https://github.com/Suwayomi/Suwayomi-Server?tab=readme-ov-file#troubleshooting-and-support)
- [x] I have updated to the **[latest version](https://github.com/suwayomi/suwayomi-server/releases/latest)**.
- [x] I have filled out all of the requested information in this form, including specific version numbers.
- [x] I understand that **Suwayomi does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.

**Comment by Syer10** [comment]
We've had a lot of issues with publishing to Winget. So it has ended up staying on an old version.

**Comment by RandomPersonUMet** [comment]
Are there any plans to start publishing to Winget again, in the future?

**Comment by Syer10** [comment]
I spent some time on it and I think I have something working, once the winget PR is merge it should be fixed. https://github.com/microsoft/winget-pkgs/pull/272145

**Comment by RandomPersonUMet** [comment]
> I spent some time on it and I think I have something working, once the winget PR is merge it should be fixed. [microsoft/winget-pkgs#272145](https://github.com/microsoft/winget-pkgs/pull/272145)

Thank you so much I really appreciate it @Syer10!

I just want to bring up that I did notice that the **Package ID** has changed, however the **Package Name** is still the same as before _(on UniGetUI)_.


<img width="1641" height="975" alt="Image" src="https://github.com/user-attachments/assets/70084597-8c21-418d-8973-b018135cfbe3" />

_All that's in Red is the same and Green has changed._


After digging through the **Winget-pkgs** for Suwayomi I found a YAML File called [Suwayomi.Suwayomi-Server.locale.en-US.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/Suwayomi/Suwayomi-Server/v2.0.1727/Suwayomi.Suwayomi-Server.locale.en-US.yaml) and noticed that it mentions **Tachidesk** numerous times _(it's the only file I found that mentions Tachidesk)_.

<img width="801" height="437" alt="Image" src="https://github.com/user-attachments/assets/184c3ed2-075c-4f2e-ae30-186220510db9" />

I'm guessing this is why the **Package Name** remains the same, despite the **Package ID** changing.

**Comment by Syer10** [comment]
Once this goes through it should all be updated https://github.com/microsoft/winget-pkgs/issues/277557
