### ISSUE TITLE
[Bug] All extension don't work - no load of mangas [SOLVED]

### ISSUE THREAD

**Issue by campana-giuseppe** [AriaMoradi/Tachidesk#367]
## Device information
- Tachidesk version: docker-tachidesk 0.6.3

After checking the resolution in the respective repository, it was defined as a general tachidesk problem.

### Actual behavior
the extensions are quietly loaded-downloaded-installed, but once opened to search for a manga they load endlessly. I've tried clearing the cache and cookies of the browser, tried incognito, set the dns of the machine with 1.1.1.1, tried from a tachidesk client that connects and reads the data correctly but even there does not load the manga from the extensions, tried multiple extensions and the same extensions work on tachiyomi. 

Obviously, the extensions have not all been fully tested. Most behave like, for example, Manganato and Mangakakalot, which after a while load the list of manga but then clicking on the individual loads nothing (the info and chapters). In some cases, however, such as the extensions of Webtoons.com and MANGA Plus by SHUEISHA, it loads the list of manga and clicking on the individual also loads the info and chapters, but then clicking on the chapter either loads indefinitely or loads empty images "notFound.svg".

**Comment by Syer10** [comment]
The only thing I can think of is that you are having a network issue since all those extensions work fine on my end. I will close this since it seems like a configuration issue, you can join the [discord server](https://discord.gg/DDZdqZWaHA) for help in the support channel.

**Comment by Robonau** [comment]
this may have been fixed in the latest preview `ghcr.io/suwayomi/tachidesk:preview` assuming it was the CRC issue

**Comment by campana-giuseppe** [comment]
> this may have been fixed in the latest preview `ghcr.io/suwayomi/tachidesk:preview` assuming it was the CRC issue

Still doesn't work. Same behaviour.
From the logs the requests to find the chapters and the related images have failed. 

example:
`Jun 22, 2022 3:21:19 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://webtoon-phinf.pstatic.net/20220509_294/1652058347507sS24A_JPEG/165205834750114681444.jpg?type=q90
Jun 22, 2022 3:21:19 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://webtoon-phinf.pstatic.net/20220509_84/1652058346569JmpjM_JPEG/165205834656214681449.jpg?type=q90
Jun 22, 2022 3:21:19 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://webtoon-phinf.pstatic.net/20220509_294/1652058347507sS24A_JPEG/165205834750114681444.jpg?type=q90 (23ms, 94244-byte body)
15:21:19.395 [DefaultDispatcher-worker-2] [1;31mERROR[0;39m suwayomi.tachidesk.server.JavalinSetup - IOException while handling the request
java.io.FileNotFoundException: /home/suwayomi/.local/share/Tachidesk/downloads/Webtoons.com (EN)/SubZero/(S2) Episode 137 Ch. 142/016.tmp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at suwayomi.tachidesk.manga.impl.util.storage.OkioExtensionsKt.saveTo(OkioExtensions.kt:28)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getCachedImageResponse(ImageResponse.kt:47)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:92)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:87)
	at suwayomi.tachidesk.manga.controller.MangaController$pageRetrieve$2$1.invokeSuspend(MangaController.kt:314)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Jun 22, 2022 3:21:19 PM okhttp3.internal.platform.Platform log`

**Comment by campana-giuseppe** [comment]
For completeness the solution in my case:

1) Make sure to use DNS such as 1.1.1.1

2) In case you use Docker, you have to pay attention to the order of the volumes you want to use as in my case where I wanted to specify the path of the downloads. The volume for downloads should be specified first and then the standard Tachidesk volume, like for example:

```
volumes:
      - /xxxx/xxxx/xxxx/:/home/suwayomi/.local/share/Tachidesk/downloads
      - /xxxx/xxxx/config/:/home/suwayomi/.local/share/Tachidesk
```
