### ISSUE TITLE
Mangadex extension is not working.

### ISSUE THREAD

**Issue by imnotadev-ineedhelp** [AriaMoradi/Tachidesk#646]
I acknowledge that:

- I have updated to the latest version of the app.
- I have tried the troubleshooting guide described in `README.md`
- This is an issue with one extension (I know) not working properly, It does work inside Tachiyomi as intended.
- I have searched the existing issues and this is a new ticket **NOT** a duplicate or related to another open issue
- I will fill out the title and the information in this template
---

## Device information
- Tachidesk version: Server: v0.7.0 + WebUI: r983
- Server Operating System: Windows 10, 10.0.19045 Build 19045.
- Server JVM version: I don't know.
- Client Operating System:  Windows 10, 10.0.19045 Build 19045.
- Client Web Browser: Brave v1.56.20 (Aug 3, 2023) and Firefox 116.0.2 (64-bit)
## Steps to reproduce
1. Add Mangadex extension.
2. Go to source section.
3. Click Mangadex.
4. Select any manga.
5. [Bug] Not working.

### Expected behavior
Should load the the manga list and info etc.

### Actual behavior
And nothing is loading, showing,
(･o･;)
Could not load manga
Request failed with status code 404

## Other details
![image](https://github.com/Suwayomi/Tachidesk-Server/assets/107185517/d7e144e1-82b7-46e4-b7c2-9bcaf4ce40ff)
![image](https://github.com/Suwayomi/Tachidesk-Server/assets/107185517/aa5a73d9-c7a6-4dc4-b9d7-cdc99aa3425c)

**Comment by schroda** [comment]
this should be fixed in the latest preview version https://github.com/Suwayomi/Tachidesk-preview/releases/latest

**Comment by idksalem** [comment]
> this should be fixed in the latest preview version https://github.com/Suwayomi/Tachidesk-preview/releases/latest

@schroda got the one u linked still does not work http://idksalem.xyz/images/4rrcl.png

**Comment by schroda** [comment]
I think you have to reinstall mangadex

**Comment by imnotadev-ineedhelp** [comment]
> this should be fixed in the latest preview version https://github.com/Suwayomi/Tachidesk-preview/releases/latest

Worked flawlessly! Thank you so much for the help <3

**Comment by dsfgorski** [comment]
I had the same problem using versions 0.7, newest stable and preview one with reinstaling mangadex extension. 
My system is Windows10 and Ubuntu on WSL2.
Here is the error from debug console:
```
Oct 15, 2023 2:43:10 AM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://api.mangadex.org/manga/6b958848-c885-4735-9201-12ee77abcb3c/aggregate?translatedLanguage[]=en (132ms, unknown-length body)
02:43:10.285 [DefaultDispatcher-worker-14] ←[1;31mERROR←[0;39m suwayomi.tachidesk.server.JavalinSetup - NullPointerException while handling the request
java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at eu.kanade.tachiyomi.lib.i18n.Intl.createBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl.access$createBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$baseBundle$2.invoke(Unknown Source)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at eu.kanade.tachiyomi.lib.i18n.Intl.getBaseBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl.access$getBaseBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl$bundle$2.invoke(Unknown Source)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at eu.kanade.tachiyomi.lib.i18n.Intl.getBundle(Unknown Source)
        at eu.kanade.tachiyomi.lib.i18n.Intl.get(Unknown Source)
        at eu.kanade.tachiyomi.extension.all.mangadex.MangaDexHelper.createManga(Unknown Source)
        at eu.kanade.tachiyomi.extension.all.mangadex.MangaDex.mangaDetailsParse(Unknown Source)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchMangaDetails$1.invoke(HttpSource.kt:184)
        at eu.kanade.tachiyomi.source.online.HttpSource$fetchMangaDetails$1.invoke(HttpSource.kt:183)
        at eu.kanade.tachiyomi.source.online.HttpSource.fetchMangaDetails$lambda$4(HttpSource.kt:183)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
        at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:34)
        at rx.Subscriber.setProducer(Subscriber.java:211)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
        at rx.Subscriber.setProducer(Subscriber.java:205)
        at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
        at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10327)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:10423)
        at rx.Observable.subscribe(Observable.java:10390)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
        at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
        at suwayomi.tachidesk.manga.impl.Manga.getManga(Manga.kt:72)
        at suwayomi.tachidesk.manga.controller.MangaController$retrieve$2$1.invokeSuspend(MangaController.kt:48)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
        at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
        ... 28 common frames omitted
```
